### ISSUE TITLE
vulnearbility detected by github

### ISSUE THREAD

**Issue by Matafou** [ProofGeneral/proofgeneral.github.io#3]
Got this message (probably other members of PG group did too) from github:

> Matafou,
> We found a vulnerable dependency in a repository you have security alert access to.
> 
> @ProofGeneral	ProofGeneral/proofgeneral.github.io
> Known high severity security vulnerability detected in nokogiri < 1.10.4 defined in Gemfile.lock.
> Gemfile.lock update suggested: nokogiri ~> 1.10.4.
> Always verify the validity and compatibility of suggestions with your codebase.

I guess I can provide a PR. Any objection?

**Comment by erikmd** [comment]
>I guess I can provide a PR. Any objection?

Thanks, go ahead!
