### ISSUE TITLE
kramdown security alert

### ISSUE THREAD

**Issue by Matafou** [ProofGeneral/proofgeneral.github.io#8]
Hi there
Should we do something about this?

https://github.com/ProofGeneral/proofgeneral.github.io/network/alert/Gemfile.lock/kramdown/open

**Comment by erikmd** [comment]
Hi @Matafou, I had a quick look, even if this vuln. only impacts the proofgeneral.github.io website, and even if the automatic dependency update **does not work this time**, it would be good to fix this, either by updating the dependency manually (but I don't have a working ruby environment at the time),
or more simply, by removing the `Gemfile.lock` (as it appears this is what has been done in the GitHub Pages upstream template repo: https://github.com/daattali/beautiful-jekyll/commit/114170ba86429da3ea2f2b658656c4089eeb9c1d)

so feel free to push a commit in master that does `git rm Gemfile.lock` (maybe I'll have a look later on on how to benefit from other upgrades from that other commit: https://github.com/daattali/beautiful-jekyll/commit/29e7fce9fc88a55bdafb507f6506bd6f153260b0, but there is no hurry)

**Comment by Matafou** [comment]
Thanks @erikmd!
